name: Build
on:
  pull_request:
    branches: ["master"]
  push:
  workflow_dispatch:
jobs:
  run-libffi-autogen:
    name: Run libffi autogen
    
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
      with:
        repository: libffi/libffi
        path: libffi
      
    - name: Run autogen
      shell: bash
      run: |
        cd libffi
        ./autogen.sh
          
    - name: Package results
      shell: bash
      run: tar -cvf libffi.tar libffi
          
    - name: Upload libffi autogen built artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libffi-autogen
        path: libffi.tar
        if-no-files-found: error
    
  build-libffi: 
    name: Build libffi
    
    needs: run-libffi-autogen
    
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
        - macOS-latest
    
    runs-on: ${{ matrix.os }}
    
    steps:
    
    - uses: actions/download-artifact@v3
      with:
        name: libffi-autogen
          
    - name: Configure libffi
      shell: bash
      run: |
        tar -xvf libffi.tar
        cd libffi
        mkdir source-build
        cd source-build          
        mkdir build
        ../configure --disable-docs --prefix $PWD/build
      
    - name: Run make
      shell: bash
      run: |
        export SHELL="/bin/sh"
        cd libffi
        cd source-build
        make install
          
    - name: Upload libffi built artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ format('libffi-build-{0}', runner.os) }}
        path: libffi/source-build/build/
        if-no-files-found: error
    
    - name: Upload libffi core library artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ format('libffi-core-build-{0}', runner.os) }}
        path: libffi/source-build/build/lib/libffi.*
        if-no-files-found: error
          
  build-constants: 
    name: Build constants library
    
    needs: build-libffi
    
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
        - macOS-latest
    
    runs-on: ${{ matrix.os }}
    
    steps:
    
    - uses: actions/checkout@v2
    
    - uses: actions/download-artifact@v3
      with:
        name: ${{ format('libffi-build-{0}', runner.os) }}
        path: libffi
         
    - name: Compile constants library
      shell: bash
      run: |
        mkdir lib

        if [ "$RUNNER_OS" == "Linux" ]; then
          export LIBRARY_EXTENSION="so"
          gcc -o lib/ffiConstants.$LIBRARY_EXTENSION -Llibffi/lib -Ilibffi/include -Wl,-rpath="@loader_path" -lffi --shared -fPIC ffiConstants/ffiConstants.c
        elif [ "$RUNNER_OS" == "macOS" ]; then
          export LIBRARY_EXTENSION="dylib"
          clang -o lib/ffiConstants.$LIBRARY_EXTENSION -Llibffi/lib -Ilibffi/include -Wl,-rpath="@loader_path" -lffi --shared -fPIC ffiConstants/ffiConstants.c
          otool -L lib/ffiConstants.$LIBRARY_EXTENSION
        fi

    - name: Upload constants library
      uses: actions/upload-artifact@v3
      with:
        name: ${{ format('ffiConstants-{0}', runner.os) }}
        path: lib
        if-no-files-found: error

  final-assembly:
    name: Final paclet assembly
    
    needs: [build-libffi, build-constants]
    
    runs-on: ubuntu-latest
      
    steps:
      
    - uses: actions/checkout@v3
    
    - name: Download macOS libffi builds
      uses: actions/download-artifact@v3
      with:
        name: libffi-core-build-macOS
        path: ForeignFunctionInterface/LibraryResources/MacOSX-x86-64/
        
    - name: Download macOS constants
      uses: actions/download-artifact@v3
      with:
        name: ffiConstants-macOS
        path: ForeignFunctionInterface/LibraryResources/MacOSX-x86-64/
        
    - name: Download Linux libffi builds
      uses: actions/download-artifact@v3
      with:
        name: libffi-core-build-Linux
        path: ForeignFunctionInterface/LibraryResources/Linux-x86-64/
        
    - name: Download Linux constants
      uses: actions/download-artifact@v3
      with:
        name: ffiConstants-Linux
        path: ForeignFunctionInterface/LibraryResources/Linux-x86-64/
        
    - name: Upload final paclet
      uses: actions/upload-artifact@v3
      with:
        name: ForeignFunctionInterface
        path: ForeignFunctionInterface/
        if-no-files-found: error
    
