name: Build
on:
  pull_request:
    branches: ["master"]
  push:
    # branches: ["master"]
  workflow_dispatch:
jobs: 
  build-libffi: 
    name: Build libffi
    
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
        - macOS-latest
    
    runs-on: ${{matrix.os}}
    
    steps:
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install MacOS script dependencies
        if: runner.os == 'macOS'
        shell: bash
        run: brew install automake
        
      - name: Run autogen
        shell: bash
        run: |
          cd libffi
          ./autogen.sh
          
      - name: Configure libffi
        shell: bash
        run: |
          cd libffi
          mkdir source-build
          mkdir build
          cd source-build
          ../configure --disable-docs --prefix $RUNNER_WORKSPACE/libffi/build
      
      - name: Run make
        shell: bash
        run: |
          cd libffi/source-build
          make install
          
      - name: Upload libffi built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libffi-build
          path: libffi/build
