name: Check Paclet
on: [push]
jobs: 
  Check-Linux: 
    name: Check Paclet
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check Paclet
      uses: WolframResearch/check-paclet@v1.7.1
      with:
        definition_notebook: "./ForeignFunctionInterface/ResourceDefinition.nb"
