name: Build
on:
  pull_request:
    branches: ["master"]
  push:
    # branches: ["master"]
  workflow_dispatch:
jobs: 
  build-libffi: 
    name: Build libffi
    
    strategy:
      matrix:
        os:
        # - ubuntu-latest
        - windows-latest
        # - macOS-latest
    
    runs-on: ${{ matrix.os }}
    
    steps:
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install macOS script dependencies
        if: runner.os == 'macOS'
        shell: bash
        run: brew install automake
        
      - name: Install Windows script dependencies
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install cyg-get
          cyg-get autoconf
          export PATH=$PATH:/usr/bin:$(cygpath ${SYSTEMROOT})/system32

#       - uses: msys2/setup-msys2@v2
#         if: runner.os == 'Windows'
#         with:
#           update: true
#           install: >-
#             base-devel
#             autoconf-wrapper
#             autoconf
#             automake
#             libtool
        
      - name: Run autogen
        shell: bash
        run: |
          export PATH=$PATH:/usr/bin:$(cygpath ${SYSTEMROOT})/system32
          cd libffi
          ./autogen.sh
          
      - name: Configure libffi
        shell: bash
        run: |
          export PATH=$PATH:/usr/bin:$(cygpath ${SYSTEMROOT})/system32
          cd libffi
          mkdir source-build
          cd source-build
          mkdir build
          ../configure --disable-docs --prefix $PWD/build
      
      - name: Run make
        shell: bash
        run: |
          cd libffi/source-build
          make install
          
      - name: Upload libffi built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('libffi-build-{0}', runner.os) }}
          path: libffi/source-build/build/
          if-no-files-found: error
