name: Build
on:
  pull_request:
    branches: ["master"]
  push:
    # branches: ["master"]
  workflow_dispatch:
jobs: 
  build-libffi: 
    name: Build libffi
    runs-on: windows-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Run autogen
        run: |
          cd libffi
          ./autogen.sh
          
      - name: Configure libffi
        run: |
          cd libffi
          mkdir source-build
          cd source-build
          mkdir build
          ../configure --disable-docs --prefix /home/runner/work/ForeignFunctionInterface/ForeignFunctionInterface/libffi/source-build/build
      
      - name: Run make
        run: |
          cd libffi/source-build
          make install
          ls -R
