name: Build
on:
  pull_request:
    branches: ["master"]
  push:
    # branches: ["master"]
  workflow_dispatch:
jobs:
  build-libffi-autogen:
    name: Build libffi autogen
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
        with:
          repository: libffi/libffi
      
      - name: Run autogen
        shell: bash
        run: |
          ./autogen.sh
          
      - name: Upload libffi autogen built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libffi-build-autogen
          path: .
          if-no-files-found: error
    
  build-libffi: 
    name: Build libffi
    
    needs: build-libffi-autogen
    
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
        # - macOS-latest
    
    runs-on: ${{ matrix.os }}
    
    steps:
    
      - uses: actions/download-artifact@v3
        with:
          name: libffi-build-autogen
          
      - name: Configure libffi
        shell: bash
        run: |
          ls -lah
          mkdir source-build
          cd source-build
          mkdir build
          ../configure --disable-docs --prefix $PWD/build
      
      - name: Run make
        shell: bash
        run: |
          cd source-build
          make install
          
      - name: Upload libffi built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('libffi-build-{0}', runner.os) }}
          path: source-build/build/
          if-no-files-found: error
