name: Build
on:
  pull_request:
    branches: ["master"]
  push:
    # branches: ["master"]
  workflow_dispatch:
jobs: 
  build-libffi: 
    name: Build libffi
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Run autogen
        run: |
          cd libffi
          ./autogen.sh
          
      - name: List files
        run: |
          realpath .
          
      - name: Configure libffi
        run: |
          cd libffi
          mkdir source-build
          cd source-build
          ../configure --disable-docs --prefix build
      
      - name: Show configured output
        run: ls -R
