name: Build
on:
  pull_request:
    branches: ["master"]
  push:
  workflow_dispatch:
jobs:
  run-libffi-autogen:
    name: Run libffi autogen
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
      with:
        repository: libffi/libffi
        path: libffi
      
    - name: Run autogen
      shell: bash
      run: |
        cd libffi
        ./autogen.sh
          
    - name: Package results
      shell: bash
      run: tar -cvf libffi.tar libffi
          
    - name: Upload libffi autogen built artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libffi-autogen
        path: libffi.tar
        if-no-files-found: error
    
  build-libffi-linux: 
    name: Build libffi (Linux)
    needs: run-libffi-autogen
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/download-artifact@v3
      with:
        name: libffi-autogen
          
    - name: Configure libffi
      shell: bash
      run: |
        tar -xvf libffi.tar
        cd libffi
        mkdir source-build
        cd source-build          
        mkdir build
        ../configure --disable-docs --prefix $PWD/build LDFLAGS=-Wl,-rpath,"@loader_path"
      
    - name: Run make
      shell: bash
      run: |
        export SHELL="/bin/sh"
        cd libffi
        cd source-build
        make install
          
    - name: Upload libffi built artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libffi-build-Linux
        path: libffi/source-build/build/
        if-no-files-found: error
    
    - name: Upload libffi core library artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libffi-core-build-Linux
        path: libffi/source-build/build/lib/libffi.*
        if-no-files-found: error
        
        
  build-libffi-macos: 
    name: Build libffi (macOS)
    needs: run-libffi-autogen
    runs-on: macOS-latest
    
    steps:
    
    - uses: actions/download-artifact@v3
      with:
        name: libffi-autogen
          
    - name: Configure libffi
      shell: bash
      run: |
        tar -xvf libffi.tar
        cd libffi
        mkdir source-build
        cd source-build          
        mkdir build
        ../configure --disable-docs --prefix $PWD/build LDFLAGS=-Wl,-rpath,"@loader_path",-install_name,"@rpath/libffi.dylib"
      
    - name: Run make
      shell: bash
      run: |
        export SHELL="/bin/sh"
        cd libffi
        cd source-build
        make install
          
    - name: Upload libffi built artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libffi-build-macOS
        path: libffi/source-build/build/
        if-no-files-found: error
    
    - name: Upload libffi core library artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libffi-core-build-macOS
        path: libffi/source-build/build/lib/libffi.*
        if-no-files-found: error
          
  build-constants-linux:
    name: Build constants library (Linux)
    needs: build-libffi-linux
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: actions/download-artifact@v3
      with:
        name: libffi-build-Linux
        path: libffi
         
    - name: Compile constants library
      shell: bash
      run: |
        mkdir lib
        gcc -o lib/ffiConstants.so -Llibffi/lib -Ilibffi/include -lffi --shared -fPIC ffiConstants/ffiConstants.c
        otool -L lib/ffiConstants.dylib
        otool -L libffi/lib/libffi.dylib

    - name: Upload constants library
      uses: actions/upload-artifact@v3
      with:
        name: ffiConstants-Linux
        path: lib
        if-no-files-found: error
        
  build-constants-macos:
    name: Build constants library (macOS)
    needs: build-libffi-macos
    runs-on: macOS-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: actions/download-artifact@v3
      with:
        name: libffi-build-macOS
        path: libffi
         
    - name: Compile constants library
      shell: bash
      run: |
        mkdir lib
        clang -o lib/ffiConstants.dylib -Llibffi/lib -Ilibffi/include -install_name @loader_path/ffiConstants.dylib -lffi --shared -fPIC ffiConstants/ffiConstants.c

    - name: Upload constants library
      uses: actions/upload-artifact@v3
      with:
        name: ffiConstants-macOS
        path: lib
        if-no-files-found: error

  final-assembly:
    name: Final paclet assembly
    
    needs:
    - build-libffi-linux
    - build-libffi-macos
    - build-constants-linux
    - build-constants-macos
    
    runs-on: ubuntu-latest
      
    steps:
      
    - uses: actions/checkout@v3
    
    - name: Download macOS libffi builds
      uses: actions/download-artifact@v3
      with:
        name: libffi-core-build-macOS
        path: ForeignFunctionInterface/LibraryResources/MacOSX-x86-64/
        
    - name: Download macOS constants
      uses: actions/download-artifact@v3
      with:
        name: ffiConstants-macOS
        path: ForeignFunctionInterface/LibraryResources/MacOSX-x86-64/
        
    - name: Download Linux libffi builds
      uses: actions/download-artifact@v3
      with:
        name: libffi-core-build-Linux
        path: ForeignFunctionInterface/LibraryResources/Linux-x86-64/
        
    - name: Download Linux constants
      uses: actions/download-artifact@v3
      with:
        name: ffiConstants-Linux
        path: ForeignFunctionInterface/LibraryResources/Linux-x86-64/
        
    - name: Upload final paclet
      uses: actions/upload-artifact@v3
      with:
        name: ForeignFunctionInterface
        path: ForeignFunctionInterface/
        if-no-files-found: error
    
