name: Build
on:
  pull_request:
    branches: ["master"]
  push:
    # branches: ["master"]
  workflow_dispatch:
jobs: 
  build-libffi: 
    name: Build libffi
    runs-on: ubuntu-latest
    steps:
      - run: ls -R
