name: Build
on:
  pull_request:
    branches: ["master"]
  push:
    # branches: ["master"]
  workflow_dispatch:
jobs: 
  build-libffi: 
    name: Build libffi
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    runs-on: ${{matrix.os}}
    
    steps:
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
#       - name: Test install
#         shell: bash
#         run: sudo apt install libffi-dev

      - name: Install script dependencies
        shell: bash
        run: |
          echo "$RUNNER_OS"
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install automake coreutils
          # elif [ "$RUNNER_OS" == "Windows" ];
          #  echo "failed"
          fi
          
      - name: Run autogen
        shell: bash
        run: |
          cd libffi
          ./autogen.sh
          
      - name: Configure libffi
        shell: bash
        run: |
          cd libffi
          mkdir source-build
          cd source-build
          mkdir build
          echo `realpath build`
          ../configure --disable-docs --prefix `realpath build`
      
      - name: Run make
        shell: bash
        run: |
          cd libffi/source-build
          make install
          ls -R
