name: Build
on:
  pull_request:
    branches: ["master"]
  push:
    # branches: ["master"]
  workflow_dispatch:
jobs: 
  build-libffi: 
    name: Build libffi
    runs-on: macos-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
#       - name: Test install
#         shell: bash
#         run: sudo apt install libffi-dev

      - name: Install automake
        shell: bash
        run: brew install automake
          
      - name: Run autogen
        shell: bash
        run: |
          cd libffi
          ./autogen.sh
          
      - name: Configure libffi
        shell: bash
        run: |
          cd libffi
          mkdir source-build
          cd source-build
          mkdir build
          ../configure --disable-docs --prefix `realpath build`
      
      - name: Run make
        shell: bash
        run: |
          cd libffi/source-build
          make install
          ls -R
