name: Build
on:
  pull_request:
    branches: ["master"]
  push:
    # branches: ["master"]
  workflow_dispatch:
jobs:
  run-libffi-autogen:
    name: Run libffi autogen
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
        with:
          repository: libffi/libffi
          path: libffi
      
      - name: Run autogen
        shell: bash
        run: |
          cd libffi
          ./autogen.sh
          
      - name: Package results
        shell: bash
        run: tar -cvf libffi.tar libffi
          
      - name: Upload libffi autogen built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libffi-autogen
          path: libffi.tar
          if-no-files-found: error
    
  build-libffi: 
    name: Build libffi
    
    needs: run-libffi-autogen
    
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
        - macOS-latest
    
    runs-on: ${{ matrix.os }}
    
    steps:
    
      - uses: actions/download-artifact@v3
        with:
          name: libffi-autogen
          
      - name: Configure libffi
        shell: bash
        run: |
          export SHELL="/bin/sh"
          tar -xvf libffi.tar
          cd libffi
          mkdir source-build
          cd source-build          
          mkdir build
          ../configure --disable-docs --prefix $PWD/build
      
      - name: Run make
        shell: bash
        run: |
          export SHELL="/bin/sh"
          cd libffi
          cd source-build
          make install
          
      - name: Upload libffi built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('libffi-build-{0}', runner.os) }}
          path: libffi/source-build/build/
          if-no-files-found: error
