name: Check Paclet
on: [push]
jobs: 
  build-libffi: 
    name: Build libffi
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - uses: actions/download-artifact@v3
      with:
       name: my-artifact
       path: path/to/artifact
    
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: path/to/artifact
