name: Check
on: 
  workflow_dispatch:
  push: 
    branches:  [main]
  pull_request: 
    branches:  [main]
env: 
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  WLPR_PACLET_SITE: https://resources.wolframcloud.com/PacletRepository/pacletsite
jobs: 
  Check: 
    name: Check
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:13.0.1
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v3
    - name: Check
      id: check-paclet-step
      uses: WolframResearch/check-paclet@v1.10.2
      with: 
        target: Submit
        definition_notebook: ./ForeignFunctionInterface/ResourceDefinition.nb
    - name: UploadWorkflowValues
      id: upload-workflow-values-step
      if: always() && env.PACLET_WORKFLOW_VALUES
      uses: actions/upload-artifact@v3
      with: 
        name: paclet-workflow-values
        path: ${{ env.PACLET_WORKFLOW_VALUES }}
        if-no-files-found: ignore
